var ArrayNomes = [
	"Aberlândio Felix Nascimento",
	"Adelmo de Jesus Santos",
	"Aderaldo Oliveira de Santan",
	"Aldo Rudney Junio Sales Santos",
	"Alexsandro de Jesus Santos",
	"Anderson Bruno Araújo Santos",
	"Antonio Carlos Moraes Andrade",
	"Antonio Gonçalves de Santana Neto",
	"Antonio Marcos Ribeiro da Silva",
	"Daniel da Silva Santos",
	"Danilo de Jesus Santos",
	"Danilo Gabriel Bomfim Santos",
	"Demas Freitas Santos",
	"Edson Cunha da Conceição",
	"Emisson de Jesus dos Santos",
	"Fabio Seixas Santos",
	"Genilson do Carmo S. Macedo",
	"George dos Santos Souza",
	"George Washington Carvalho dos Santos da Silva",
	"Geovane Resende de Santana",
	"Gustavo Freitas Santos",
	"Jailson Souza dos Santos",
	"Jilvan Angelo dos Santos",
	"Joao Cleber Santana Leal de Abreu",
	"Joao Pedro de Jesus Doria",
	"Joelmir Santos Gonzaga",
	"José Adenio Ribeiro do Nascimento",
	"Jose Alves de Oliveira Neto 10/10/1992",
	"Jose Amilton dos Santos Matos",
	"Jose Andre Correia dos Santos",
	"José Arnaldo dos Santos",
	"José Cleidisson das Virgens Santos",
	"José Doglas Santna Leal",
	"Jose Edenilson de Jesus Santos",
	"Jose Jeovan de Jesus Santana",
	"Jose Leandro dos Santos",
	"Jose Micael Cruz Matos",
	"José Miraldo da Silva Santos",
	"Jose Romario Cruz Andrade",
	"Jose Santos de Santana",
	"Juliano Santos Santana",
	"leandro Alves de Souza",
	"Leonardo Paulo dos Santos",
	"Leonardo Souza de Andrade",
	"Luizinho Reis Leal",
	"Maciel de Jesus Ferreira",
	"Marcos Vinicius de Melo",
	"Marcos Vinicius Santana Fontes",
	"Marcos Vinicius Santos Rocha",
	"Matheus Silva Santana",
	"Nadson Santos Santana",
	"Normilson Conceição dos Santos",
	"Paulo César de C. Reis",
	"Paulo Henrique dos Santos",
	"Pedro Henrique Silva",
	"Rafael Barbosa Ramos",
	"Railton de Santana Santos",
	"Rerinaldo dos Santos Lima",
	"Rodrigo Santana Alves",
	"Uilson Santos de Jesus",
	"Vinicius Andrade dos Reis",
	"Wemerson Oliveira de Carvalho",
	"Willans da Conceicão",
	"Willian Carvalho Morais",
	"Ygor Frances Santos da Conceicão"
];



module.exports = ArrayNomes;